data:
  path: /mnt/iusers01/mace01/d26811ms/scratch/pk_256x256_raw_10-179wires.pt

output:
  dir: /mnt/iusers01/mace01/d26811ms/scratch/models
  splits_dir: /mnt/iusers01/mace01/d26811ms/scratch/training
  inference_dir: /mnt/iusers01/mace01/d26811ms/scratch/inference
