data:
  path: /Volumes/easystore/proton-kaon/images/pk_48x48_log1p.pt
  proton: p
  kaon: k
  val_split: 0.1
  random_seed: 42

model:
  type: vae
  latent: 4
  dropout: 0
  input_hw: [48, 48]

optimizer:
  lr: 0.001
  weight_decay: 0.0001

train:
  epochs: 200
  batch_size: 32
  beta: 10.0

output:
  dir: /Volumes/easystore/proton-kaon/models
  splits_dir: /Volumes/easystore/proton-kaon/training
  inference_dir: /Volumes/easystore/proton-kaon/inference